# .github/workflows/project3-tests.yml
name: Autograde Project 3

on:
  pull_request:
    paths:
      - "projects/project-3/**"
      - ".github/workflows/project3-tests.yml"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: projects/project-3/assignment

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug paths
        run: |
          echo "PWD=$(pwd)"
          ls -la
          echo "Repo root:"
          ls -la "$GITHUB_WORKSPACE"
          echo "Listing src/data for sanity:"
          ls -la src/data || true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            # Fallback if requirements.txt missing
            pip install pytest rdflib pandas openpyxl
          fi

      - name: Run tests
        run: pytest -q
